# Generated by Django 5.1.3 on 2024-12-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите чат ID в Telegram",
                max_length=50,
                null=True,
                verbose_name="Telegram чат ID",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="tg_nick",
            field=models.CharField(
                blank=True,
                help_text="Укажите свой ник в telegram",
                max_length=50,
                null=True,
                verbose_name="Тelegram ник",
            ),
        ),
    ]
